# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 741de9c779fea47dde1ba7ac7e7f06f40809548aebbf664536b59e640960f6d0a02c1451c126539398acc6892c4d1f3ca481791ff89c9b86deaa8cca02bf0b98

test:
  secret_key_base: 433f280b23460e70cc091a264239354b37be4bb0347751c1951ebeb963287a06c7aa279a6c4d4d4007eb8c12ca52064a34339eea128635e9bcbc76115e4b657c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
